id: brew:container-compose
display-name: container-compose
homepage: https://github.com/mcrich23/container-compose
repo: https://github.com/Mcrich23/container-compose
package-manager:
  brew: container-compose
  macports: container-compose
package-manager-url: https://formulae.brew.sh/formula/container-compose
license: Apache-2.0
description: Manage Apple Container with Docker Compose files
executables:
  - container-compose
provenance:
  formula: container-compose
  provider: brew
  source: https://formulae.brew.sh/api/formula.json
